name: CI - Multi-Stage E-Commerce Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint - ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, auth, product-api]
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint || echo "No lint script defined"

  test:
    name: Test - ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service: [frontend, auth, product-api]
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "No test script defined"

  build:
    name: Build - ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [frontend, auth, product-api]
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Build (only for frontend)
        if: matrix.service == 'frontend'
        run: npm run build
  
  docker-build:
    name: Build and Push - ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [frontend, auth, product-api]
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List Dockerfile for debug
        run: pwd && ls -l
        

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest \
                 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
